### ISSUE TITLE
how to bulid the souce code

### ISSUE THREAD

**Issue by Blue-Design** [phptuts/ArduinoBlocklyIDE#14]
I am  familiar with arduino and blockly, but not electron. I want to konw how to bulid this project, and I think I will help this project become better.

**Comment by phptuts** [comment]
So sorry for the late response.  

To start the project run 
```
yarn start
``` 
This will build it for the dev environments.  Because I have to sign the code you can't really build it.  Let me know if that's what you are looking for.

**Comment by phptuts** [comment]
Closing this issue.  Please let me know how I can help you.  @Blue-Design
